### ISSUE TITLE
Import CSV-Files startet nicht

### ISSUE THREAD

**Issue by SKU101971** [solectrus/csv-importer#161]
Hallo,
ich versuche alte CSV-Files von SENEC zu importieren und erhalte beim Import folgende Fehlermeldung:

```
Importing data from /data ...
Importing /data/S20972121431523342540029526-week-1-2023.csv... bundler: failed to load command: app/main.rb (app/main.rb)
/usr/local/lib/ruby/3.2.0/net/http.rb:1603:in `initialize': Failed to open TCP connection to influxdb:8086 (getaddrinfo: Name does not resolve) (SocketError)
```

Es scheint, als wenn der Port 8086 nicht zur Verbindung der Datenbank verfügbar wäre.

In der docker-compose.yml habe ich in Zeile 63-64 folgende Änderungen durchgeführt:

    # Optional: Allow InfluxDB to be accessed from the outside.
    ports:
      - 8086:8086

Dennoch läßt sich auch nach einem Reboot des Raspberry PI kein Import durchführen. Es kommt immer die gleiche Fehlermeldung.

Hat jemand eine Idee, was ich noch probieren kann?

**Comment by ledermann** [comment]
Grundsätzlich ist es so, dass ein Reboot **keine** Änderung an der Konfiguration von Docker-Containern vornimmt. Nach einem Reboot laufen die Container genauso weiter, wie sie vorher waren, Änderungen an `docker-compose.yml` oder `.env` werden also **nicht** übernommen.

Die Container müssen stattdessen **neu erstellt** werden. Das geht mit `docker compose up -d`. Dieser Befehl startet nicht nur die Container, sonst erstellt sie bei Bedarf (wenn Änderungen an der Konfiguration festgestellt werden) auch neu.

Um ganz sicherzugehen, kannst du vorher noch ein `docker compose down` durchführen, aber das ist nur ein Ausnahmefällen (bei Änderungen an Netzwerken oder Volumes) nötig.

**Comment by SKU101971** [comment]
Ich habe die Speicherkarte für Solectrus von Anfang an neu eingerichtet und vor dem aller ersten docker compose up die Anpassungen in der docker-compose.yml vorgenommen. Leider weiterhin das selbe Ergebnis. Es kann keine Verbindung über den Port 8086 aufgebaut werden.
Ein docker compose down und anschließender docker compose up -d hat ebenfalls keinen Erfolg gezeigt.

**Comment by ledermann** [comment]
Gibt es vielleicht Probleme mit dem Docker-Netzwerk? In deinem obigen Output ist erkennbar, dass der Host "influxdb" verwendet wird. Dieser muss natürlich auch erreichbar sein, was er wohl nicht ist. Daher verwendet das `docker run`-Statement den Parameter `--network=solectrus_default`, um sich mit dem Netzwerk zu verbinden, das `docker-compose.yml` aufgebaut hat.

Wenn das nicht hilft: Poste bitte mal Details zu deinem Setup, insbesondere `.env`, `docker-compose.yml` und das verwendete `docker run`-Statement. Und den Output von `docker ps` zum Zeitpunkt des Imports.

**Comment by SKU101971** [comment]
Danke für die Hilfe. Jetzt geht es. Es lag tatsächlich am Docker-Netzwerk. Ich habe das falsche Netzwerk verwendet,
