### ISSUE TITLE
Import csv-Dateien aus SENEC

### ISSUE THREAD

**Issue by stocki1972** [solectrus/csv-importer#199]
Hallo,
ich habe ziemliche Probleme mit dem Import. Das fängt schon mal damit an, dass ich auf der Speicherkarte keine .env-Datei finde. Somit weiß ich auch nicht, wo ich den csv-Ordner erstellen soll. Ich habe dazu die Speicherkarte aus dem Raspberry rausgenommen und mittels Kartenleser mit meinem MacBook verbunden. Dann mit dem Finder gesucht...

Kann mir jemand das für Dummies erklären: ich habe keine Ahnung von den Befehlen. Ich weiß gerade noch, wie ich mich per SSH mit meinem Raspberry Pi verbinde.
Solectrus habe ich gemäß der Anleitung installiert. Keine Ahnung, wie ich das geschafft habe.

Kann mir jemand helfen und mir das Schritt für Schritt für Dumme erklären?

Vielen Dank
VG Martin

**Comment by stocki1972** [comment]
Hallo,

Sind die Befehle nach dem Einloggen per ssh dann zeilenweise einzeln einzugeben, oder im Block?
Am 1. Mai 2024, 12:11 +0200 schrieb Georg Ledermann ***@***.***>:

**Comment by ledermann** [comment]
> Sind die Befehle nach dem Einloggen per ssh dann zeilenweise einzeln einzugeben, oder im Block?

1. Befehl: `cd ...`
2. Befehl: `docker run ...`, das ist **ein** Befehl, die Backslashes (`\`) signalisieren, dass sich der Befehl über mehrere Zeilen erstreckt. Also en bloc ausführen.
3. Befehl: `docker exec ....`

**Comment by stocki1972** [comment]
Hmmmm,

Die Ordnerstruktur meiner SD-Karte sieht folgendermaßen aus (den csv-Ordner hab ich einfach mal in die oberste Ebene kopiert)

Nix von home/pi/solectrus …..

Am 1. Mai 2024, 15:40 +0200 schrieb Georg Ledermann ***@***.***>:

**Comment by ledermann** [comment]
Falls du einen Screenshot angehangen hast, den sieht man den hier auf GitHub nicht. Antwort per E-Mail ist eine Notlösung, besser direkt hier auf GitHub schreiben. Hier kannst du auch Bilder hochladen, falls nötig.

Unabhängig davon: Die Sache mit der SD-Karte ist sowieso nicht optimal, möglicherweise gibt es Probleme mit Zugriffsrechten. Mit `scp` geht es sowieso einfacher. Hier eine Anleitung:

1) Auf dem Mac: Öffne ein Terminalfenster und wechsele mit `cd` in den Ordner, in dem die CSV-Dateien liegen. Mache dann das hier:

```
scp -r . pi@raspberrypi:/home/pi/solectrus/csv
```

Damit wird der Inhalt des aktuellen Ordners auf deinem Mac (also `.`) mit allen Unterordner (`-r`) auf den Rechner `raspberrypi` in den dortigen Ordner `/home/pi/solectrus/csv/` kopiert. Unter Verwendung des Users `pi`. Passe das Kommando ggfs. an, falls der User oder der Raspi bei dir anders heißen sollten. Bei Unklarheiten mit `scp` am besten nach Hilfestellung und der genauen Syntax googeln.

2) Anschließend dann SSH-Login, zum Ordner navigieren und dann das Docker-Kommando ausführen.

**Comment by stocki1972** [comment]
Hat geklappt. Vielen Dank für deine Bemühungen!!!

VG
Martin
Am 1. Mai 2024, 12:11 +0200 schrieb Georg Ledermann ***@***.***>:
>
> docker exec -it solectrus-redis-1 redis-cli FLUSHALL
