### ISSUE TITLE
Fehler bei Zusammengefassten Werten Jahr und Geasmt

### ISSUE THREAD

**Issue by AlpenFlizzer** [solectrus/csv-importer#217]
Ich habe den CSV-Importer geforked und Unterstützung für das SolarEdge CSV Format implementiert (csv-Exports kann man unter [monitoring.solaredge.com ](https://monitoring.solaredge.com/) nach eigenem Bedarf erzeugen)
https://github.com/AlpenFlizzer/csv-importer/tree/import_solaredge_record 

Ich habe für den Gesamt-Export von 10.2021 bis 04.2024 Tageswerte und für den Mai 2024 habe ich Stundenwerte.

Grundsätzlich hat der Import funktioniert, ich bekomme für die Daten mit Tageswerten alles korrekt angezeigt (habe es gegen das Solaredge Dashboard gecheckt) in den Anzeigen für Tag, Woche und Monat. In der Jahresansicht für 2021-2023 passen die Daten auch. zB für 2023:
![grafik](https://github.com/solectrus/csv-importer/assets/47642539/efed5fc8-b180-4c82-a228-4daaf60ea545)

In der Jahresansicht für 2024 sind die Daten in der linken Visualisierung zu hoch, wobei die Daten in den Graphen rechts wiederum für die Monate korrekt sind. Dieser Fehler schlägt auf die Gesamtansicht durch.

![grafik](https://github.com/solectrus/csv-importer/assets/47642539/7f2d2490-1fa9-461b-b9ba-2c1701549d61)
![grafik](https://github.com/solectrus/csv-importer/assets/47642539/0d6e9b8b-456b-41e6-8d66-a9df11d9ded3)

Ich habe in Influx alle Daten exported und zum eine festgestellt, dass im Mai die Kurven wie "falsch skaliert" aussehen und dass Daten aus der Zukunft vorhanden sind...

![grafik](https://github.com/solectrus/csv-importer/assets/47642539/6bb967be-6825-491c-a07c-4849909747c5)

Solectrus bekommt die PV Daten von evcc via MQTT-Collector (seit 30.05.2024) alles davor sind import Daten.

Ausgangsdatensatz ist folgendes CSV: 
[data.csv](https://github.com/solectrus/csv-importer/files/15496205/data.csv)

Aus Influx alles in CSV gedumpt ist folgendes: 
[query.csv](https://github.com/solectrus/csv-importer/files/15496208/query.csv)

Ich betreiebe einen kompletten Test-Stack, kann also jederzeit alles wegwerfen und neu machen - für jeglichen Input oder Tipp wäre ich dankbar. Ich würde gerne die Solaredge App durch Solectrus ablösen, in Kombination mit evcc für das Energiemanagement ergibt sich tolles Optimierungspotential. (Bin deshalb übrigens ein Fan von der Idee generische Verbraucher wie Heizung usw. über den MQTT-Collector von evcc in Solectrus zu pushen)

Ich bin auf solectrus:next und mqtt-collector:develop, die restlichen images sind wie im hosting Guide beschrieben. (hatte beides auch schon auf latest)

Danke! LG Sascha

**Comment by ledermann** [comment]
Interessante Arbeit! Bin daran interessiert, dass wir das hinbekommen.

Was mir so auffällt:

- Hast du für die alten Jahre wirklich nur Tageswerte? Lassen sich keine höher aufgelösten Daten bei SolarEdge herunterladen? 
- Tageswerte müssen umgerechnet werden. Es ist ja so, dass in InfluxDB nicht die **Energie** (in Wh) abgelegt wird, sondern die **Leistung** (in W). Falls wirklich nur die Energie pro Tag zur Verfügung steht, könnte man diese in eine Durchschnittsleistung umrechnen: Durch 24 dividieren und dann 24-mal mit jeweils angepasstem Zeitstempel speichern. Die von SOLECTRUS verwendeten Flux-Abfragen gehen davon aus, dass Daten mindestens im Stunden-Turnus vorhanden sind.
- Der Zeitstempel in `query.csv` erscheint mir seltsam, beim Attribut `time` liegen immer mehrere Tage zwischen den einzelnen Zeilen.
- Hast du bedacht, dass nach **jedem** Import der Redis-Cache zurückgesetzt werden muss? Ansonsten passieren die seltsamsten Dinge: `docker exec -it solectrus-redis-1 redis-cli FLUSHALL`

Ich übernehme deinen Code gerne ins offizielle Repo, sobald alles funktioniert. Ich kann mir das gerne auch selber ansehen, sofern die vorliegende `data.csv` wirklich das Beste ist, was man von SolarEdge herunterladen kann.

**Comment by AlpenFlizzer** [comment]
Dann will ich das Pferd nochmal neu aufsatteln. Folgende Möglichkeiten Daten zu beschaffen gibt es:

1. Predefined Exports für Tage und Wochen (beide 15-Min Auflösung), Monat (Tagesdaten) und Jahr (Monatsdaten)
![grafik](https://github.com/solectrus/csv-importer/assets/47642539/c8219b42-34fb-4d7b-9530-247a5545c354)
Übrigens fände ich solche überlagerten Graphen extrem gut in Solectrus. :-) 

Da bekommt man per Default Daten wie folgt raus:

zB. Woche:
```
Time,Bezug (W),Energie - Eigenverbrauch (W),Exportieren (W),Produktion (W),Verbrauch (W)
24.05.2024 00:00,"403.862","0","0","0","403.862"
24.05.2024 00:15,"474.8209","0","0","0","474.8209"
24.05.2024 00:30,"515.1322","0","0","0","515.1322"
24.05.2024 00:45,"451.8848","0","0","0","451.8848"
24.05.2024 01:00,"459.3293","0","0","0","459.3293"
24.05.2024 01:15,"507.4242","0","0","0","507.4242"
24.05.2024 01:30,"417.4517","0","0","0","417.4517"
24.05.2024 01:45,"437.9027","0","0","0","437.9027"
24.05.2024 02:00,"503.4705","0","0","0","503.4705"
24.05.2024 02:15,"405.0481","0","0","0","405.0481"
24.05.2024 02:30,"442.9395","0","0","0","442.9395"
24.05.2024 02:45,"516.5724","0","0","0","516.5724"
24.05.2024 03:00,"475.4182","0","0","0","475.4182"
24.05.2024 03:15,"526.9081","0","0","0","526.9081"
24.05.2024 03:30,"549.9697","0","0","0","549.9697"
24.05.2024 03:45,"388.7947","0","0","0","388.7947"
24.05.2024 04:00,"438.3652","0","0","0","438.3652"
24.05.2024 04:15,"486.1223","0","0","0","486.1223"
24.05.2024 04:30,"409.6717","0","0","0","409.6717"
24.05.2024 04:45,"473.9936","0","0","0","473.9936"
24.05.2024 05:00,"543.3494","0","0","0","543.3494"
24.05.2024 05:15,"456.7953","10.2989","0","10.2989","467.0942"
24.05.2024 05:30,"442.9935","57.9272","0","57.9272","500.9207"
24.05.2024 05:45,"410.5688","106.5772","0","106.5772","517.1459"
24.05.2024 06:00,"310.3565","121.5195","0","121.5195","431.876"
24.05.2024 06:15,"368.1015","148.884","0","148.884","516.9856"
24.05.2024 06:30,"609.116","357.8948","0","357.8948","967.0107"
24.05.2024 06:45,"125.721","334.7607","0","334.7607","460.4816"
24.05.2024 07:00,"227.22","345.6706","0","345.6706","572.8906"
24.05.2024 07:15,"44.2643","528.2716","289.6619","817.9335","572.5359"
24.05.2024 07:30,"0","498.9651","1076.0795","1575.0446","498.9651"
24.05.2024 07:45,"0","538.0165","1615.6503","2153.6667","538.0165"
24.05.2024 08:00,"0","1110.3564","1046.3987","2156.7551","1110.3564"
24.05.2024 08:15,"1830.5605","1109.4686","0","1109.4686","2940.0293"
...
```
zB. Monat:
```
Time,Bezug (Wh),Energie - Eigenverbrauch (Wh),Exportieren (Wh),Produktion (Wh),Verbrauch (Wh)
01.05.2024,"9509","14050","35671","49721","23559"
02.05.2024,"8722","9884","29634","39518","18606"
03.05.2024,"12130","13558","6409","19967","25688"
04.05.2024,"8153","12080","41114","53194","20233"
05.05.2024,"8528","12211","35279","47490","20739"
06.05.2024,"9839","12107","29344","41451","21946"
07.05.2024,"13457","7332","4555","11887","20789"
08.05.2024,"13939","9019","9213","18232","22958"
09.05.2024,"6623","10950","45356","56306","17573"
10.05.2024,"11010","14895","34722","49617","25905"
11.05.2024,"8234","9981","38541","48522","18215"
12.05.2024,"7538","13418","42591","56009","20956"
...
```

zB. Jahr:
```
Time,Bezug (Wh),Energie - Eigenverbrauch (Wh),Exportieren (Wh),Produktion (Wh),Verbrauch (Wh)
01.01.2024,"866725","217799","120694","338493","1084524"
01.02.2024,"564672","209447","211487","420934","774119"
01.03.2024,"534315","300509","486933","787442","834824"
01.04.2024,"407323","324843","737196","1062039","732166"
01.05.2024,"270541","370336","862036","1232372","640877"
01.06.2024,"0","0","0","0","0"
01.07.2024,"0","0","0","0","0"
01.08.2024,"0","0","0","0","0"
01.09.2024,"0","0","0","0","0"
01.10.2024,"0","0","0","0","0"
01.11.2024,"0","0","0","0","0"
01.12.2024,"0","0","0","0","0"
...
```

2. Costom Exports, die nochmal andere Daten und andere Auflösungen für einen Zeitraum zulassen.
Beispiel: Wechselrichter AC-Leistung, Einspeiseleistung und Bezugsleistung
![grafik](https://github.com/solectrus/csv-importer/assets/47642539/ad0d8410-f4fb-4634-a1cf-c49c8cede03e)

- Leider muss man alles händisch exporten, daher muss man entscheiden wie viel Aufwand einem die Auflösung wert ist. Außerdem kann man nur eine begrenzte Anzahl von Datenquellen in einen Export packen, das ist aber recht random und ich weiß nicht welche Daten wirklich wichtige wären für Solectrus.

Überblick Zeitraum/max. Auflösung:
- 1 Tag bis 1 Woche: 5 Minuten
- ab 1 Woche bis 4 Wochen: 15 Minuten
- ab 4 Wochen bis 364,95 Tage: Stündlich
- ab 365 Tage bis ?: Täglich

Welche Daten sind deiner Meinung nach in welcher Auflösung ideal? Dann kann ich den Importer ja nochmal anpassen.
Seltsam ist, dass trotz nur täglicher Daten meines ersten Versuchs und den 3-Tages Lücken in query.csv trotzdem die berechneten Werte aus Solectrus mit den Werten aus Solaredge für Einspeisung, Verbrauch usw. für Tag, Woche, Monat und Jahre 2021-2023 übereinstimmen...

**Comment by ledermann** [comment]
Danke für den Überblick! Grundsätzlich denke ich, je höher die Auflösung, desto besser ist es. Aber wenn die Erstellung der CSV-Daten so aufwändig ist, dann lohnt sich das vermutlich eher nicht. 

Selbst mit einer Auflösung von nur 24h kann man ja arbeiten. Ich hatte das gleiche Problem bei meiner Wärmepumpe, da lagen mir aus technischen Gründen für den Anfangszeitraum auch nur Tagessummen (in kWh) vor. Die habe ich dann (wie oben schon erwähnt) einfach aufgeteilt, hier ein Beispiel:

Tagessumme = 10,9 kWh
Durchschnitt pro Stunde: 10,9 / 24 = 0,454167 kW
24 Messwerte nach InfluxDB importiert:

    00:00 Uhr   0,454167 kW
    01:00 Uhr   0,454167 kW
    ...
    23:00 Uhr   0,454167 kW

Das Ergebnis ist dann eine konstante Linie:
https://demo.solectrus.de/heatpump_power/2024-02-17

Da man im Nachhinein kaum wissen muss, wie genau der Tagesverlauf war, reicht das vollkommen. Die korrekte Summenbildung von Monat und Jahr bleibt damit weiterhin möglich.

Für die Implementierung schlage ich nun vor, die ursprüngliche Datei `data.csv` zu nehmen. In jeder Zeile muss dann geprüft werden, ob es sich um eine Tagessumme handelt (weil Uhrzeit fehlt) oder ob es sich um eine Stundensumme handelt (weil Uhrzeit vorhanden). Bei einer Tagessumme müssen 24 Records erstellt werden (mit Wert / 24), bei einer Stundensumme ist keine Umrechnung nötig.

Dass die Darstellung in bestimmten Fällen bei dir dennoch stimmte, liegt wohl daran, dass SOLECTRUS bei einigen Abfragen mindestens einen Wert pro Stunde erwartet, bei anderen Abfragen aber nicht. Genauer habe ich das aber nicht untersucht.

**Comment by AlpenFlizzer** [comment]
Ich habe heute so ziemlich den ganzen Tag damit verbracht nochmal die Exportmöglichkeiten der Solaredge Plattform, den Import in Solectrus und auch einen Vergleich der Daten zwischen HomeAssistant+SolaredgeModbus, Solectrus+MQTTviaEVCC und den Auswertungen von Solaredge gemacht.

Es hat sich herausgestellt, dass alle drei Plattformen verschiedene Werte für Produktion, Bezug, Einspeisung und Verbrauch anzeigen, wobei sich HomeAssistant und Solectrus den selben Datenlieferant bedienen (Modbus-proxy, der am Solaredge WR hängt). Die Solaredge Plattform bekommt die Daten sonstwie in deren Cloud.

Ich habe für einen Tag auch die Daten in 5, 15 und 60 Minuten Auflösung (sowohl Energie, als auch Leistung die ich dann umgerechnet habe) exportiert und in Excel die Werte gegengerechnet - die waren auch wieder anders als die anderen drei und je Auflösung kamen auch unterschiedliche Werte heraus.

Es handelt sich meist um eine Abweichung von +-0,2 bis 2kWh.

Die Daten, die live von evcc via MQTT gepublisht werden und vom MQTT-Collector in Solectrus gespeichert werden passen übrigens auch nicht mit den Werten bei Solaredge zusammen.
![grafik](https://github.com/solectrus/csv-importer/assets/47642539/cb4af276-581f-4234-b25f-d40c446a4999)
Falls du einen Blick riskieren willst, von diesem Tag die Daten in den höchsten möglichen Auflösungen:
Influx: [29052024influx.csv](https://github.com/user-attachments/files/15518100/29052024influx.csv)
Aus Solaredge ein Custom Export: [29052024solaredge_custom.csv](https://github.com/user-attachments/files/15518108/29052024solaredge_custom.csv)
Aus Solaredge ein Predefined Export: [29052024solaredge_predefined.csv](https://github.com/user-attachments/files/15518110/29052024solaredge_predefined.csv)

Ich werde es jetzt nochmal mit Tageswerten für Leistung in W versuchen und schauen was rauskommt. Wenn du selbst einen Versuch starten willst, könnte ich die Rohdaten bereitstellen. Aber offensichtlich ist der Importer mein kleinstes Problem. Ich konnte im Solectrus code nicht die Stellen finden, wo die Daten für die Anzeige berechnet werden um zu verstehen was Solectrus da macht.

**Comment by AlpenFlizzer** [comment]
Habe es eben so wie du vorgeschlagen hast versucht: Tageswerte für die Wh exportiert, Durchschnittswerte für 24 Stunden berechnet und mit Timestamps für jede Stunde importiert.
Die Werte stimmen auf diese Weise mit denen der Solaredge Plattform überein.
Wie du sagtest, zeigen die Graphen nur eine konstante Linie - das trifft zu, wobei er keine Linie macht sondern nur "unsichtbare" Datenpunkte.

Bis jetz habe ich das CSV mit Python preprocessed (ChatGPT ist mein Freund...) und am Importer nichts geändert. Diese Tageswert->Durchschnitts-Stundenwert Konversion müsste wohl in der Import Klasse passieren, die wäre dann aber nicht mehr so generisch wie bishher (zumindest nicht mit meinen Dev Skills).

**Comment by ledermann** [comment]
Wenn ich dich richtig verstehe, hat der Import jetzt geklappt, auch wenn die Daten in mehreren Schritten konvertiert wurden. Klingt gut! Was ich aber nicht verstehe: 

> Wie du sagtest, zeigen die Graphen nur eine konstante Linie - das trifft zu, wobei er keine Linie macht sondern nur "unsichtbare" Datenpunkte.

Du meinst, in SOLECTRUS ist keine solche Linie erkennbar? Das ist seltsam und erscheint mir falsch. Es sollte so aussehen wie bei meinem angegebenen [Link zur Wärmepumpe](https://demo.solectrus.de/heatpump_power/2024-02-17).

Ich würde gerne auf Basis [deines Codes](https://github.com/solectrus/csv-importer/compare/develop...AlpenFlizzer:csv-importer:import_solaredge_record) den offiziellen CSV-Importer erweitern. Könntest du mir dazu eine Referenz-CSV-Datei geben, idealerweise sowohl mit alten Zeilen (nur Tagessumme) **und** neuen Zeilen (Stundensummen)? Ich vermute, dass die `data.csv` von ganz oben eine solche sein könnte. Wichtig ist auch, dass die Spalten-Bezeichnungen korrekt sind.

Die Berechnung der Stundendurchschnitte würde dann direkt im CSV-Importer erfolgen, wenn eine Zeile nur ein Datum enthält, also keine Uhrzeit. Ziel sollte sein, dass man eine unveränderte CSV-Datei nehmen kann, die man bei SolarEdge herunterladen kann und die dann ohne manuelle Zwischenschritte importiert wird.

**Comment by AlpenFlizzer** [comment]
![grafik](https://github.com/solectrus/csv-importer/assets/47642539/ab309c68-65ee-4185-8918-81eb6c9ff842)
So sieht es aus. Der Datenpunkt ist da, aber keine Linie.

Eingabedatei vor Konversion: [input.csv](https://github.com/user-attachments/files/15521853/input.csv)
Ausgabe Datei nach Konversion: [output.csv](https://github.com/user-attachments/files/15521855/output.csv)

Wie du siehst, passe ich während der Konversion die Spaltenüberschriften an, aber das kann man auch lassen und den Importer auf die originalen Solaredge Spaltenüberschriften konfigurieren.

Ich bin den code nochmal durchgegangen und der wäre für eine Eingabedatei wie die verlinkte tauglich.

**Comment by ledermann** [comment]
Das mit der fehlenden Linie irritiert mich sehr. Ich werde das mal selber angehen, PR #220 ist angelegt. Melde mich dann wieder.

**Comment by ledermann** [comment]
Habe jetzt ein wenig aufgeräumt und Code ergänzt, siehe #221. 

Es müssen leider 5-Minuten-Abschnitte sein, damit die Grafiken stimmen. Ich könnte das im Dashboard anpassen, will aber jetzt nicht zu viel auf einmal ändern.

@AlpenFlizzer: Aus meiner Sicht sieht das nun alles korrekt aus, wie siehst du das?

**Comment by AlpenFlizzer** [comment]
Ich habe den Teststack weggeworfen und neu gebaut. Habe den Importer aus deinem neuen Branch geclont und obige Eingabedatei damit importiert. Der Import an sich scheint zu funktionieren, das Chart zeigt jetzt die linien mit den rechnerisch korrekten 5-minuten Werten, dafür stimmen die Zahlen in der Tile Ansicht nicht mehr. Influx und CSV Daten stimmen dabei überein und wenn ich 288*Value aus einem beliebigen Chart rechne komme ich auch auf den Wert der rauskommen sollte.

![grafik](https://github.com/solectrus/csv-importer/assets/47642539/ce69e51e-8d51-4074-9251-25f48599aff4)
0,17*288=48,96 (lt. Solaredge 49kWh) lt. Grafik links 4,1kWh

Übrigens kommt das gleiche Ergebnis dabei raus, wenn ich die Daten vorab mit Python in 5-Minuten Daten konvertiere (dafür dann die Umrechnung im Importer auskommentiere). Es müsste also eher was mit Solectrus als dem Importer zu tun haben.

**Comment by ledermann** [comment]
Mea culpa, das hätte mir selbst auffallen müssen, sorry! 

Es muss anders gerechnet werden: Die Tagesenergie (49 kWh) muss zunächst in eine konstante Leistung umgerechnet werden, also dividiert durch 24, somit 2,04 kW. Und dieser Wert wird dann 288-mal geschrieben.

Habe meinen Code korrigiert und noch Tests ergänzt. Jetzt stimmts:

![30. Mai 2024](https://github.com/solectrus/csv-importer/assets/3557/96185888-45e8-42cf-b72a-7010c7249468)

**Comment by AlpenFlizzer** [comment]
Habe eben deinen letzten Commit getestet und ja, jetzt funktioniert es. Danke für deine Mühe an der Stelle! :-)

Was mir noch aufgefallen ist: in den Tagesansichten sind die Werte verglichen zur Solaredge Plattform immer noch ca. 0,2kWh off. In den Monatsansichten sind sie aber gleich. Mir ist schon vorher aufgefallen, dass ich bei Exporten aus Influx immer die Werte mit UTC Zeit bekomme, also wenn ich den 30.5. aus Influx exporte bekomme ich 2h vom Vortag aber dafür am eigentlichen Tag nur bis 22 Uhr Werte. Kann diese Abweichung in der Tagesansicht an unterschiedlicher Verasrbeitung der Zeiten/Zeitzonen in Solectrus und Influx liegen? Bei den Monatswerten ist ja die Zeitzone denke ich egal?

Aber das könnten wir auch in einem seperaten Issue nachvollziehen. Dieser hier ist resolved.
Danke nochmal für deinen Support und die Mühe.

**Comment by ledermann** [comment]
Aufgrund deines Hinweises habe ich mir nochmal genauer die Influx-Queries von SOLECTRUS angesehen. Und tatsächlich, da gab es eine Ungenauigkeit, die bislang nicht erkannt wurde. Ich habe das gerade korrigiert. 

Am Beispiel des 30. Mai lässt sich erkennen, dass jetzt die Summen in der Strombilanz exakt deinen SolarEdge-Werten entsprechen:

![31. Mai 2024](https://github.com/solectrus/csv-importer/assets/3557/f53a56b7-5dc9-497d-b4e6-4ca908717548)

Die Korrektur ist im `develop`-Branch enthalten. Wenn du diesen ausprobieren magst, ändere deine `docker-compose.yml` auf:

```
image: ghcr.io/solectrus/solectrus:develop
```

Mit der Zeitzone hat das übrigens nichts zu tun. Der CSV-Importer (und auch das Dashboard) verwendet standardmäßig die Zeitzone `Europe/Berlin`. Bei beiden kann dies über die Umgebungsvariable `TZ` geändert werden. 

InfluxDB erlaubt grundsätzlich, die Zeitzone bei Abfragen zu berücksichtigen. SOLECTRUS verwendet beispielsweise eine solche Query für die Berechnung der Summen:

```influxdb
from(bucket: "my-bucket")
  |> range(start: 2024-05-30T00:00:00+02:00, stop: 2024-05-30T23:59:59+02:00)
  |> filter(fn: (r) => r["_measurement"] == "my-pv-measurement" and (r["_field"] == "inverter_power" or r["_field"] == "house_power" or r["_field"] == "grid_power_plus" or r["_field"] == "grid_power_minus"))
  |> aggregateWindow(every: 1h, fn: mean)
  |> sum()
```

(beachte die Zeitstempel bei `range`, `+02` ist MESZ)
