### ISSUE TITLE
Anpassung an Sensor-Konfiguration

### ISSUE THREAD

**Issue by ledermann** [solectrus/csv-importer#282]
Der Importer verwendet noch die alten, SENEC-spezifischen Field-Names, also noch nicht die neue [Sensor-Konfiguration](https://github.com/solectrus/solectrus/wiki/Konfiguration#sensor-konfiguration).

Somit ist der CSV-Importer derzeitig **nicht** kompatibel zu einer Konfiguration, die mit dem Konfigurator für einen **anderen** Stromspeicher als SENEC erstellt wurde.

**Comment by hambue** [comment]
Ich hatte aufgrund eines fehlerhaften Firmware-Updates 10 Tage keinen lokalen Zugriff auf meinen Speicher. Meine Konfigurationsdateien wurden nicht mit dem Konfigurator erstellt, ich habe sie allerdings ab Version 15 so geändert, dass sie das neue Sensor-Mapping enthalten. Kann ich den aktuellen CSV-Importer noch verwenden oder sollte ich auf das Schließen dieses Issues warten?

**Comment by ledermann** [comment]
Der Importer schreibt derzeitig noch fix in diese Fields:

- `inverter_power`
- `house_power`
- `bat_power_plus`
- `bat_power_minus`
- `bat_charge_current`
- `bat_voltage`
- `grid_power_plus`
- `grid_power_minus`

@hambue Ich nehme ab, du hast einen SENEC-Speicher. Wenn in deiner Installation von SOLECTRUS diese Fields so existieren (wovon ich ausgehe), dann kannst du den Importer problemlos auch in der jetzigen Fassung verwenden.

Was hier in diesem Issue von mir zu tun ist: Einlesen der Sensor-Konfiguration und schreiben der Werte in die konfigurierten Measurements/Fields.

**Comment by hambue** [comment]
Ja, hat alles geklappt. Danke.

**Comment by hj-hefer** [comment]
Hallo Georg,

Kommt noch ein Update für den neuen Konfigurator oder ist das zu aufwendig?

**Comment by ledermann** [comment]
@hj-hefer Mit dem Konfigurator hat der CSV-Importer eigentlich gar nichts zu tun. Oder verstehe ich dich falsch?

Was hier (in diesem Issue) noch offen ist: Aus der `.env` muss die Sensor-Konfiguration entnommen werden, sodass der CSV-Importer in die konfigurierten Felder der InfluxDB schreibt, also nicht statisch nach `grid_power_plus` etc. Relevant ist das für die Nutzer von SOLECTRUS, die **keinen** SENEC-Stromspeicher haben, sondern etwas anderes - und daher andere Fieldnames in ihrer InfluxDB stehen haben.

Wenn du also einen SENEC-Stromspeicher hast und CSV-Dateien importieren möchtest, kannst du den CSV-Importer in der derzeitigen Fassung verwenden.

**Comment by hj-hefer** [comment]
Ich beziehe mich auf den Eintrag

[Fehlermeldung beim Import](https://github.com/solectrus/csv-importer/issues/282#top)
#280 

Hab ja eine neue Version eingerichtet mit dem Konfigurator. Hab einen Senec V3 Speicher und mit diesem csv Import geht es ja noch nicht.

**Comment by ledermann** [comment]
@hj-hefer Wenn du einen SENEC-Stromspeicher hast, sollte der CSV-Importer im jetzigen Zustand funktionieren. Mir ist nicht klar, was genau bei dir nicht funktioniert. Importierst du möglicherweise ins falsche Measurement?

Bei anhaltenden Probleme bitte ein Diskussionsthema aufmachen und darin die jetzige Konfiguration posten (`compose.yaml` und `.env`) und erklären, was genau nicht klappt:
https://github.com/orgs/solectrus/discussions/new?category=q-a

**Comment by cjungde** [comment]
Ich hänge mich hier mal dran: 
Ich habe meinen SENEC speicher for kurzem durch ein anderes Fabrikat ersetzt (Sigenergy) und daher die chance genutzt Solectrus komplett neu auf einem Proxmox Docker mit dem MQTT Collector aufzusetzen. 
Nun würde ich gerne meine alten SENEC Daten seit 2018 in das neue System laden. Soweit ich es verstehe funktioniert das noch nicht. Auf jeden Fall werden nach dem Import derzeit noch keine Daten im Dashboard angezeigt. 
Gibt es etwas das ich tun kann, um den Import passend aufzubereiten ?

**Comment by ledermann** [comment]
@cjungde Bitte nicht bestehende Issues mit eigenen Fragen ergänzen, das führt zu Chaos. Hier in diesem Issue geht es darum, den Importer an die neue Konfiguration anzupassen. Derzeitig funktioniert der Importer nur, wenn die Sensoren auf die alten SENEC-Feldnamen eingestellt sind (`inverter_power`, `house_power`, `bat_power_minus` usw.)

Bei weiterem Klärungsbedarf bitte **nicht** hier kommentieren, sondern ein neues Diskussionsthema aufmachen.

**Comment by ledermann** [comment]
Ich bin das Thema nun angegangen und habe den Importer so umgebaut, dass die Sensor-Konfiguration aus der `.env` berücksichtigt wird. Die Änderung ist Teil von `v0.5.0`.

Somit ist der CSV-Import jetzt kompatibel zur Konfiguration, die mit dem Konfigurator erstellt wurde, auch für Sungrow und SolarEdge.

**Comment by cjungde** [comment]
Ich habe es gerade erfolgreich getestet >> funktioniert bei mir !
