### ISSUE TITLE
Importer schreibt Integer, Dashboard erwartet Float

### ISSUE THREAD

**Issue by ledermann** [solectrus/csv-importer#55]
Nach Import erscheint im Dashboard ein Error 500, im Log steht:

```
ts=2023-07-02T11:41:01.650491Z lvl=info msg="Execute source panic" log_id=0imbISV0000 service=storage-reads error="panic: interface conversion: tsm1.Value is tsm1.IntegerValue, not tsm1.FloatValue" 
[...]
app_1                 | I, [2023-07-02T11:41:01.652988 #11]  INFO -- : [172.18.0.1] method=GET path=/stats/inverter_power/now format=html controller=StatsController action=index status=500 duration=229.82 view=0.00 user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
app_1                 | F, [2023-07-02T11:41:01.655709 #11] FATAL -- : [172.18.0.1]   
app_1                 | [172.18.0.1] ActionView::Template::Error (panic: interface conversion: tsm1.Value is tsm1.IntegerValue, not tsm1.FloatValue):
app_1                 | [172.18.0.1]      5: turbo-stream action="morph" target="stats" children-only= true
app_1                 | [172.18.0.1]      6:   template
app_1                 | [172.18.0.1]      7:     - if timeframe.now?
app_1                 | [172.18.0.1]      8:       = render StatsNow::Component.new calculator:, field:
app_1                 | [172.18.0.1]      9:     - else
app_1                 | [172.18.0.1]     10:       = render StatsRange::Component.new calculator:, timeframe:, field:
app_1                 | [172.18.0.1]   
app_1                 | [172.18.0.1] app/services/flux/reader.rb:59:in `query_without_cache'
app_1                 | [172.18.0.1] app/services/flux/reader.rb:49:in `block in query'
app_1                 | [172.18.0.1] app/services/flux/reader.rb:48:in `query'
app_1                 | [172.18.0.1] app/services/power_peak.rb:3:in `result'
app_1                 | [172.18.0.1] app/components/stats_now/component.rb:24:in `peak'
app_1                 | [172.18.0.1] app/components/stats_now/component.html.slim:4:in `call'
app_1                 | [172.18.0.1] app/views/stats/index.turbo_stream.slim:8
app_1                 | [172.18.0.1] app/controllers/stats_controller.rb:6:in `index'
app_1                 | [172.18.0.1] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
app_1                 | I, [2023-07-02T11:41:01.673906 #11]  INFO -- : [172.18.0.1] method=GET path=/500 format=html controller=ErrorsController action=show status=500 duration=17.13 view=16.69 user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
```

Wie es scheint, gibt es noch ein Problem mit Float vs. Integer

**Comment by ledermann** [comment]
@holiday-sunrise Ich kann das Problem leider noch nicht reproduzieren. 

Was ich gemacht habe:

1. InfluxDB neu aufgesetzt (lokal via Docker)
2. CSV-Datei aus #54 mit csv-importer v0.3.1 importiert (für den 28.06.2023)
3. SOLECTRUS lokal mit dieser InfluxDB gestartet -> der Tag 28.06.2023 wird mit Daten korrekt angezeigt. Alles andere ist leer, aber fehlerfrei

Ich vermute hier irgendeine Wechselwirkung mit dem MQTT-Collector, allerdings schreibt der auch nur Integer, keine Floats.

Kannst Du mir einen Weg aufzeigen, wie sich das Problem reproduzieren lässt? 

Grundsätzlich würde ich vorschlagen, zunächst ausschließlich mit importierten Daten zu testen. Erst wenn das klappt, sollte der MQTT-Collector hinzugenommen werden.

**Comment by holiday-sunrise** [comment]
Ich habe Dir mal einen Abzug der Daten nach dem 18.06 gemacht. Hilft Dir das ?
[query (3).csv](https://github.com/solectrus/csv-importer/files/11930931/query.3.csv)

Ich kann Dir gern ein Backup der DB zusenden ?!?

**Comment by holiday-sunrise** [comment]
Wenn ich nur importiere und dann den MQTT hinzunehme dann kracht es.

**Comment by ledermann** [comment]
Ok, das ist ja schon mal ein nützlicher Hinweis. MQTT-Collector und CSV-Importer produzieren also irgendeinen Konflikt. 

Um sicherzustellen, dass keine fehlerhaften Daten aus älteren Versuchen vorhanden sind, ist es vermutlich das einfachste, das Influx-Docker-Volume komplett zu löschen und dann noch mal neu zu starten.

Mein Vorschlag:

1. Alles runterfahren (docker compose down)
2. Redis-Ordner löschen
3. InfluxDB-Ordner löschen
4. SOLECTRUS neu starten. Prüfen, ob sich alles aufrufen lässt
5. Mit csv-Importer alte Daten importieren, dann Redis Flush ALL
6. In SOLECTRUS durchklicken, ob alle Daten da sind (bei TAG,WOCHE/MONAT/JAHR) und fehlerfrei angezeigt werden
7. MQTT-Collector starten
8. Erneut in SOLECTRUS prüfen, ob die Daten reinkommen (bei JETZT)

Falls das Problem dann wieder auftritt (also Fehler 500 mit "panic: interface conversion: tsm1.Value is tsm1.IntegerValue, not tsm1.FloatValue"), dann weiß ich erst mal nicht weiter. Mir ist auch die Aussage dieser Fehlermeldung nicht klar.
Ich müsste dann mal hier versuchen, das alles bei mir nachzustellen.

Nebenbei: Laut obigem Stacktrace tritt der Fehler bei JETZT auf. Dort wird alle 30 Tage ein Peak ermittelt, um das UI optimal zu skalieren. Die hierfür verwendete InfluxDB-Query kommt bei den anderen Zeiträumen nicht zum Einsatz. Es wäre also interessant zu wissen, ob der Fehler 500 wirklich nur bei JETZT auftritt oder auch noch woanders.

**Comment by holiday-sunrise** [comment]
Werde ich morgen mal testen

**Comment by holiday-sunrise** [comment]
Hallo Georg ich habe mal alles neu aufgesetzt und es hat alles funktioniert. Danke für deine Hilfe. CSV-Importer ist Sungrow approved

**Comment by ledermann** [comment]
Bestens, das freut mich sehr. Vielen Dank für Deine Mühe!
