### ISSUE TITLE
Sungrow: Wo ist die Einspeisung?

### ISSUE THREAD

**Issue by ledermann** [solectrus/csv-importer#56]
Bei der Betrachtung der [CSV-Daten von Sungrow](https://github.com/solectrus/csv-importer/blob/develop/spec/data/sungrow/Tagesbericht_20230621.csv) frage ich mich, wo sich denn da die Werte für die Einspeisung verstecken? 

Ich hatte zunächst vermutet und auch so implementiert, dass die Angabe der Spalte `Netz (W)` sowohl positiv (=Netzbezug) als auch negativ (=Einspeisung) sein kann, aber negative Werte scheinen gar nicht vorzukommen.

@holiday-sunrise Weißt Du genaueres dazu?

**Comment by holiday-sunrise** [comment]
Hi, 

einspeisen kannst du noch nicht sehen da meine Anlage dies wegen einem Fehlenden Zähler noch nicht erlaubt.

Sonst wäre Netz Negativ denke ich.

Beste Grüße

Rainer

**Comment by ledermann** [comment]
Das ist eine gute Erklärung, somit ist beim csv-Importer nichts zu tun.
