### ISSUE TITLE
bundler: failed to load command: app/main.rb (app/main.rb)

### ISSUE THREAD

**Issue by jacitty** [solectrus/csv-importer#76]
Beim Versuch, alle .csv-Dateien mittels 
`docker run -it --rm --env-file .env --mount type=bind,source="$PWD/csv",target=/data,readonly --network=solectrus_default ghcr.io/solectrus/csv-importer`

zu importieren bekomme ich diese Meldung:

> CSV importer for SOLECTRUS, Version 0.3.2, built at 2023-07-22T13:13:57.993Z
> https://github.com/solectrus/csv-importer
> Copyright (c) 2020-2023 Georg Ledermann, released under the MIT License
> 
> bundler: failed to load command: app/main.rb (app/main.rb)
> /csv-importer/app/config.rb:39:in `fetch': key not found: "INFLUX_MEASUREMENT_PV" (KeyError)
> Did you mean?  "INFLUX_TOKEN_READ"
> 	from /csv-importer/app/config.rb:39:in `from_env'
> 	from app/main.rb:17:in `<top (required)>'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:58:in `load'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:23:in `run'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/cli.rb:492:in `exec'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/cli.rb:34:in `dispatch'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/cli.rb:28:in `start'
> 	from /usr/local/bundle/gems/bundler-2.4.17/exe/bundle:37:in `block in <top (required)>'
> 	from /usr/local/bundle/gems/bundler-2.4.17/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
> 	from /usr/local/bundle/gems/bundler-2.4.17/exe/bundle:29:in `<top (required)>'
> 	from /usr/local/bundle/bin/bundle:25:in `load'
> 	from /usr/local/bundle/bin/bundle:25:in `<main>'

**Comment by ledermann** [comment]
Ist die `.env`-Datei vielleicht schon älter? Die Variable `INFLUX_MEASUREMENT_PV` ist kürzlich hinzugekommen.

Im Zweifelsfall bitte im Hosting-Guide nachgucken:
- https://github.com/solectrus/hosting/blob/main/guide/raspberry-pi/.env
- https://github.com/solectrus/hosting/blob/main/guide/raspberry-pi/docker-compose.yml

**Comment by jacitty** [comment]
Danke für die Info. 

Da hab ich dann schon mein Problem mit meinen automatischen Updates in der Nacht, dass ich nicht mit bekommen, ob was aktualisiert wurde, und ggf. was aktualisiert wurde und ob ich manuell noch was machen muß. Mal sehen, wie ich das hin bekomme, da benachrichtigt zu werden.

**Comment by ledermann** [comment]
Grundsätzlich versuche ich, Updates so zu gestalten, dass keinerlei Eingriffe nötig sind, damit eben eine völlig automatische Aktualisierung möglich ist. Ich stimme dir zu, dass man nicht bei jedem Update gezwungen sein sollte, nachzusehen, ob alles noch funktioniert.

Manchmal ist das nicht möglich oder es schleichen sich Fehler ein. Letzteres ist hier passiert - die genannte Variable ist hinzugekommen, aber es gibt keinen Fallback. Genau den habe ich gerade ergänzt, das wird im nächsten Update des CSV-Importers enthalten sein.

Falls du deine Updates mit Watchtower durchführst, können dort übrigens Benachrichtigungen konfiguriert werden:
https://containrrr.dev/watchtower/notifications/
