### ISSUE TITLE
Zeitzone des Imports stimmt nicht

### ISSUE THREAD

**Issue by hambue** [solectrus/csv-importer#88]
Da ich gestern sehr viele NPU-Fehler hatte, habe ich die (deutsche Senec-)CSV für diese Woche importiert. Die Werte einer Uhrzeit in der CSV wurden allerdings alle 2 Stunden zu spät in Solectrus eingetragen. Soll heißen: Mein Ertrag war laut CSV um 8 Uhr 0,7kW, in Solectrus wird dieser Betrag dann aber erst um 10 Uhr angezeigt.

Ich habe dann die Umgebungsvariable _TZ= Europe/Berlin_ in meine bisherige _.env_-Datei eingetragen. Danach wurden die Container einmal runtergefahren und wieder neugestartet. Das hatte allerdings keine Auswirkungen beim nächsten Import-Versuch.

An welchen Variablen könnte man hier noch drehen, dass der Abgleich wieder passt?

Edit: Mir ist gerade eingefallen, dass die von mir hinzugefügte TZ Variable nicht in der docker-compose.yml steht. Findet der CSV-Importer sie dann überhaupt?

**Comment by ledermann** [comment]
Du hast recht, da stimmt etwas mit der Zeitzone nicht - eines der Lieblingsprobleme aller Entwickler ;-) 

Lokal auf dem Mac kann ich es zwar nicht reproduzieren, aber auf dem Raspi über Docker werden die Zeitstempel nicht korrekt nach InfluxDB übertragen - es gibt einen Zeitversatz von 2 Stunden.

Nun sind in Deiner InfluxDB leider falsche Daten enthalten - sehr ärgerlich. Für eine pragmatische und schnelle Lösung schlage ich vor, die InfluxDB-Datenbank ganz zu löschen und sämtliche Daten aus den CSV neu zu importieren (mit korrigierter Zeitzone), da die InfluxDB nun falsche Daten enthält. 

**ACHTUNG:** Dadurch verlierst Du einige Messwerte, z.B. Wallbox, Temperatur, Ladestand etc., weil diese in den CSV-Dateien nicht enthalten sind. Bitte nur fortfahren, wenn das akzeptabel für Dich ist!

Löschen und korrigierter Neuimport geht wie folgt:

- `cd solectrus` 
- `docker compose down`
- `sudo rm influxdb/*`
- `sudo rm redis/*`
- In `.env` ergänzen: `TZ=UTC-2` (**wichtig!**)
- Import neu starten mit `docker run ...` (siehe [README](https://github.com/solectrus/csv-importer#usage))

Warum es `UTC-2` sein muss, verstehe ich gerade selbst noch nicht. Der Sache werde ich noch auf den Grund gehen, vermutlich wird es ein Update des CSV-Importers geben müssen.

**Comment by hambue** [comment]
Danke für die schnelle Einordnung des Problems. Da ich nur diese Woche und die erste Woche nach der Inbetriebnahme importiert habe, hält sich das Ärgernis in Grenzen. Ich werde ich wohl auf ein Löschen der InfluxDB verzichten, da mir die Temperaturdaten wertvoller erscheinen.

**Comment by ledermann** [comment]
Ich habe das Problem nun korrigiert und die neue Version v0.3.5 veröffentlicht. Diese verwendet jetzt standardmäßig "Europe/Berlin" als Zeitzone, über die Variable TZ kann eine andere Zeitzone gewählt werden.

Die Konfiguration einer Zeitzone ist übrigens deshalb notwendig, weil die Zeitstempel in den CSV-Dateien OHNE Zeitzone notiert sind.
